import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import { FaSearch } from "react-icons/fa";
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <ConnectButton />
        </header>
        

        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a>
        </h1>
        <div className={styles['search-container']}>
            <FaSearch id="search-icon" className={styles['search-icon']}/>
            <input 
              type="text"
              // ref={inputtedText}
              placeholder="paste a Twitter handle ..."
              onKeyDown={(e) => { if (e.key === 'Enter') { handleSearch(); }}}
            />
            </div>

      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by Lostin
        </a>
      </footer>
    </div>
  );
};

export default Home;
